---
title: "capstone_proposal_2"
author: "becker"
date: '2018-07-16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Capstone Project Proposal

Increase customer upgrades.

#### About Wishpond (Client)

Wishpond is an All-in-one Marketing Suite for Retailers and Brand. Our suite includes social contest and promotions app that permits you to run unlimited vote contests, sweepstakes, and campaigns. It additionally supplies a number of alternative tools such as landing page creators, email marketing and marketing automation.


### What is the problem you want to solve?
The goal of the capstone project is to analyze Wishpond’s current customer actions on the platform, and understand better the main features that leads to an upgrade. 


### Who is your client and why do they care about this problem? In other words, what will your client DO or DECIDE based on your analysis that they wouldn’t have otherwise?
As mentioned above, the client is Wishpond. We expect the client to have a better understanding of its customers’ action and what it takes for a customer to upgrade their plan. By understanding its customers' action on the platform, Wishpond will be able to focus on the features that are highly correlated to upgrades and increase their revenue.


### What data are you going to use for this? How will you acquire this data?
I’ll be using my client’s internal database. The database is located in Woopra, a customer analytics platform. 


### In brief, outline your approach to solving this problem (knowing that this might change later).
The approach is to analyze the customer current plans and their actions on Wishpond's platform such as if they have created a landing page, a pop-up, a form, have visited our blog, have talked to Wishpond customer support, had a demo with one our sales agent and so on. The focus is to understand what of these actions have high correlation with each of these plans and make recommendations on how each customer should be treated based on their plan.


### What are your deliverables? Typically, this would include code, along with a paper and/or a slide deck.
The project will provide the code of for all the analysis and also a graphs which states the work that is being done. It will also provide an overall report which gives a brief explanation to the solution taken to achieve our goal.

