---
title: "machine_learning_markdown"
author: "becker"
date: '2018-08-03'
output: html_document
---
```{r setup, include=FALSE, echo = FALSE}
load("wp_data.RData")
library("dplyr")
library("tidyr")
library("ggplot2")
library("mice")
library("caTools")
library("ROCR")
```


### Machine Learning Project

##### This project will use machine learning to predict the risk of a customer unsubscribing from Wishpond. 

##### This is a supervised problem because we are attempting to predict a specific dependent variable using a model based on a set of independent variables.

##### This is a classfication problem

##### The independent variable is Unsubscribed, FALSE or TRUE.

##### This project will be using different techniques, first it will use multiple imputation to fill the missing values with predict values and logistic regression to predict if customer are at high risk of unsubscribing or not.

##### It will be test by using a train/test split in the database, evaluate the accuracy percentage with the baseline and analyze AUC to see if the model has a high percentage value to differentiate from those who have unsubscribed.
